### ISSUE TITLE
Bard token doesn't want to work

### ISSUE THREAD

**Issue by Sliganyth** [dsdanielpark/Bard-API#108]
this is the current code = https://hastebin.skyra.pw/jezekuquwe.py
the error = https://hastebin.skyra.pw/ohanafegon.pgsql

there was before another issue that the token wasn't finishing on the dot. i fixed it by changing "{YOUR BARD TOKEN}"
to 'YOUR BARD TOKEN'

**Comment by Sliganyth** [comment]
this is the current code = https://hastebin.skyra.pw/jezekuquwe.py
the error = https://hastebin.skyra.pw/ohanafegon.pgsql

there was before another issue that the token wasn't finishing on the dot. i fixed it by changing "{YOUR BARD TOKEN}"
to 'YOUR BARD TOKEN'

**Comment by dsdanielpark** [comment]
This occurs when requests are not sent successfully due to reasons such as network issues, proxy servers, port forwarding, and other factors unrelated to token values. 

There is no issue with [the code](https://hastebin.skyra.pw/jezekuquwe.py) itself, so please try running it in Colab or a different network environment.

If you search the issue using proxy or similar error as criteria, you may find relevant results, such as #99 and so on.

**Comment by Sliganyth** [comment]
Maybe its not compatible with spotify api when its running the localhost server?

**Comment by dsdanielpark** [comment]
It could be a case where the calls are not possible due to Google's internal API interface policies rather than compatibility issues with other APIs. If you are using the bardapi package independently, it is uncertain whether you will be able to use it successfully.
