### ISSUE TITLE
Max retries exceeded with url (host='bard.google.com', port=443): 

### ISSUE THREAD

**Issue by Jacky1y** [dsdanielpark/Bard-API#113]
requests.exceptions.ProxyError: HTTPSConnectionPool(host='bard.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1091: The handshake operation timed out')))

**Comment by dsdanielpark** [comment]
*It may not work as it is only available for certain accounts, regions, and other restrictions.*

Moreover, since I cannot invoke the method in my region and account, I have no choice but to rely on the contributors' debugging. I am eagerly awaiting contributions from an active community. 

Thank you in advance for your contribution.
