### ISSUE TITLE
Failed to maintain the conversation content

### ISSUE THREAD

**Issue by Arkuus** [dsdanielpark/Bard-API#114]
Hello, I am currently using your project. I've built a web page with Flask, but I've failed to maintain the conversation content. I have tried your installation methods, but I still haven't been successful. Each conversation is new. Could you provide me with some solutions? Could it be that the methods are no longer valid due to the official update on July 13th?  

Here's my app.py code:  
```
from flask import Flask, render_template, request
from bardapi import Bard
import os
import requests
import json

app = Flask(__name__)

session = requests.Session()
session.headers = {
    "Host": "bard.google.com",
    "X-Same-Domain": "1",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
    "Origin": "https://bard.google.com",
    "Referer": "https://bard.google.com/",
}
os.environ['_BARD_API_KEY'] = 'XXXXXX'
session.cookies.set("__Secure-1PSID", os.getenv("_BARD_API_KEY"))

@app.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        user_input = request.form.get('user_input')
        token = os.environ["_BARD_API_KEY"]
        bard = Bard(token=token, session=session, timeout=30)
        response = bard.get_answer(user_input)
        ai_response = response['content']
        conversation_id = response['conversation_id']
        return json.dumps({'answer': ai_response, 'cid': conversation_id})
    return render_template('home.html')

if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True)
```

**Comment by dsdanielpark** [comment]
Excluding the new features, the operation of the get_answer method is valid. 

After conducting several tests, I will provide you with a response again. 

However, it has been consistently reported and confirmed that there are various limitations such as location, account, and network status, which may prevent the reproduction from a different IP address even with the same account. 

Although I have confirmed that it is functioning properly, due to various factors such as your environment's settings, it may not be possible to configure it.
