### ISSUE TITLE
Exception: SNlM0e value not found in response. Check __Secure-1PSID value.

### ISSUE THREAD

**Issue by mikey-joyce** [dsdanielpark/Bard-API#118]
I have this error when trying to make a request. I have checked the __Seecure-1PSID value and it is correct. I know that the Bard developers updated Bard recently, when I tried to log in on my browser it prompted me with a captcha to make sure I wasn't a robot. Will this API be screwed because of this?

**Comment by dsdanielpark** [comment]
Due to recent updates, I am unable to provide accurate answers. There are various situations occurring with functionalities that are not supported in my country and specific to individual accounts. However, if you have entered the correct values, please try restarting your browser or clearing your cookies. Alternatively, you can refer to https://github.com/dsdanielpark/Bard-API#auto-cookie-bard and try using the following code.

Please close all windows and try calling the following method while logged in to your Chrome Incognito browser.
```
from bardapi import Bard

bard = Bard(token_from_browser=True)
res = bard.get_answer("Do you like cookies?")
print(res)
```

**Comment by mattbarron** [comment]
I was having the same issue. Someone in a previous thread suggested it had something to do with being logged into multiple google accounts and to try an incognito window, logging in and getting the cookie value from there. That worked for me.

**Comment by thewh1teagle** [comment]
@sudipkumarbhattacharya 
Please try to use bard first from your browser, and then copy the cookie value and try again from python
If it doesn't work, sign out from all google accounts in your computer, and then sign in to bard from `google chrome`
after you finish, update bard api library as follow:
```python
pip3 install -U bardapi
```
And then run this code as is:
```python
from bardapi import Bard

bard = Bard(token_from_browser=True)
res = bard.get_answer("Do you like cookies?")
print(res)
```

**Comment by mikey-joyce** [comment]
The solution for me was the refresh the cookies in my browser.
