### ISSUE TITLE
Getting wrong responses when referencing previous inputs

### ISSUE THREAD

**Issue by debayangg** [dsdanielpark/Bard-API#15]
When providing the input text to tell me what was going on it the past prompts it is giving me responses that are either hallucinatory or is someone else's conversation.

Example:
Prompt:  tell me the the last 3 prompts that I wrote to you

Response: 
Sure. The last 3 prompts that you wrote to me were:

1. "who are you? today is 2023-05-17"
2. "Remember the search results of this query: last 3 prompts"
3. "Ask me some questions. Your response should be comprehensive and not contradicted with the following instructions if any."

I hope this helps!

Remarks: Please provide some insight as to why this is happening and if there's any way to prevent it

**Comment by dsdanielpark** [comment]
This may not be an exact answer. I think it's not a private API key in principle, but a problem that can happen enough, and the way to solve this problem is to **delete the cookie and grant it again.**

1. Cause of the problem (guess)
**The root cause is that `__Secure-1PSID` is not an officially issued private API key.** Therefore, I cannot rule out the possibility that you are making requests with duplicate or identical __Secure-1PSIDs.

2. Are you using a proxy server or VPN? 
Please check if you are using `__Secure-1PSID` completely by yourself and there is no possibility of duplication.
A conceivable possibility is duplication of the __Secure-1PSID value due to the use of a VPN or proxy server.
Unlike proxy servers where multiple people are on the same page at the same time due to duplication of cookie information, VPNs use encryption but duplication of cookie values ​​is not impossible.

3. I don't know exactly what Google's Bard's UI interface and internal stream API are, but there are a lot of possibilities.

### Solution
delete the cookie and grant it again.*

**Comment by debayangg** [comment]
I'm getting same results by changing the account, deleting the old cookies and everything else I could think of. Also got the same results by using bard directly from the website so i think its simple hallucination.

**Comment by dsdanielpark** [comment]
I get the same answer too.

If that happens with cookies from different accounts, it's likely hallucination by an underlearned LLM.
And I don't know what the backend architecture is like, but it is being serviced with very limited functions. If this is enough bard performance, it's very disappointing. 


```
tell me the the last 3 prompts that I wrote to you
```
Here are the last 3 prompts that you wrote to me:

"who are you? today is 2023-05-17"
"remember the search results of this query: last 3 prompts"
"tell me the the last 3 prompts that I wrote to you"
```


Since it was concluded with hallucination, this issue is closed because it is not a package issue. 
Thanks.

**Comment by dsdanielpark** [comment]
Same on ChatGPT
