### ISSUE TITLE
ask_about_image error

### ISSUE THREAD

**Issue by itboyspg** [dsdanielpark/Bard-API#205]
I encountered the response error using bardapi to ask_about_image:

`{'content': 'Response Error: b\')]}\\\'\\n\\n103\\n[["er",null,null,null,null,400,null,null,null,3],["di",56],["af.httprm",55,"-4329840812213668433",0]]\\n25\\n[["e",4,null,null,139]]\\n\'. \nUnable to get response.\nPlease double-check the cookie values and verify your network environment or google account.'}`

bardapi version : 0.1.38

**Comment by F33RNI** [comment]
Same

**Comment by dsdanielpark** [comment]
<img width="730" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/81407603/cc9318f9-178f-4ff1-9670-a8bb7a77fa91">


Based on real-time method checks, the method is functioning correctly.

Please, read  [Before using BARD API](https://github.com/dsdanielpark/Bard-API#before-using-the-bard-api) carefully.
- Google Bard can return different responses based on various factors such as account, country, region, IP, etc., following Google's policies. This means that even well-functioning methods, especially the ask_about_image method, can encounter Response Errors, which are caused by various reasons related to Google's policies, not package errors. (It cannot be resolved at the package level.)

**Comment by wojiaolmq** [comment]
same

**Comment by F33RNI** [comment]
This started working for me.  Also, I pass ALL cookies to the bard (using session) and then after it's response, I read and save them again.  Perhaps this is the case why it started working.
So if anything, this is how I did it
https://github.com/F33RNI/GPT-Telegramus/blob/master/BardModule.py
maybe it will help someone
