### ISSUE TITLE
Response Error - Unable to get response

### ISSUE THREAD

**Issue by MananAg-1784** [dsdanielpark/Bard-API#206]
I executed this following command to use the Bard API : 
from bardapi import Bard, BardCookies

cookie_dict = {
    "__Secure-1PSID" : "xxxxxxxxxxxxxxxxxxxxxx",
    "__Secure-1PAPISID" : "xxxxxxxxxxxxxxxxxxxxx",
    "__Secure-1PSIDCC" : "xxxxxxxxxxxxxxxxxxxxx",
}
bard = BardCookies(cookie_dict = cookie_dict)

result = bard.get_answer("how to use ChatGPT?")
print(result['content'])

I am still getting a response error :
Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",367],["af.httprm",367,"2847306205436971809",7]]\n25\n[["e",4,null,null,131]]\n'.
Unable to get response.
Please double-check the cookie values and verify your network environment or google account.

**Comment by dsdanielpark** [comment]
#128 

# Troubleshooting Google Account-Related Issues with Bard API

```python
Response Error: b')]}\\'\\n\\n38\\n[[\"wrb.fr\",null,null,null,null,[8]]]\\n54\\n[[\"di\",59],
[\"af.httprm\",59,\"4239016509367430469\",0]]\\n25\\n[[\"e\",4,null,null,129]]\\n'. 
Temporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.
```

The error you're experiencing isn't originating from the package itself; it's related to your Google account and may be due to various factors like your country or region settings, which can prevent you from receiving accurate results from Bard. Therefore, it's beyond the scope of the package to resolve, but please consider checking the following:

1. First, thoroughly read the readme and see if it pertains to cases of temporary abnormal responses from the package. Try again after some time or a few hours: [Before using Bard API](https://github.com/dsdanielpark/Bard-API/blob/main/README.md#before-using-the-bard-api)
2. Bypass proxies: [Behind a proxy](https://github.com/dsdanielpark/Bard-API#behind-a-proxy)
3. Try using an account from a different region or change the language settings of your Google account.
4. Restart your browser to refresh the cookie values and use the new __Secure-1PSID.
5. Try passing three or more cookies using [Multi-cookie Bard](https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_DEV.md#multi-cookie-bard). If that doesn't work, consider passing almost all cookie values.

Please let me know if you need further assistance.

**Comment by dsdanielpark** [comment]
If you cannot receive a normal response in your area, try making the request through [Crawlbase's ](https://crawlbase.com/)anonymous [smart proxy service.](https://crawlbase.com/docs/smart-proxy/get/) (Still, be mindful of Google's rate limiting, so adjust the time between requests and avoid requesting duplicate responses.)

```
$ pip install bardapi
```

```python
from bardapi import Bard
import requests

proxy_url = "http://xxxxxxxxxxxxxx:@smartproxy.crawlbase.com:8012"
proxies = {"http": proxy_url, "https": proxy_url}

bard = Bard(token='xxxxxxx', proxies=proxies, timeout=30)
bard.get_answer("나와 내 동년배들이 좋아하는 뉴진스에 대해서 알려줘")['content']
```

**Comment by botsmaster** [comment]
> #128
> # Response Issues with Bard API
> 
> ```python
> Response Error: b')]}\\'\\n\\n38\\n[[\"wrb.fr\",null,null,null,null,[8]]]\\n54\\n[[\"di\",59],
> [\"af.httprm\",59,\"4239016509367430469\",0]]\\n25\\n[[\"e\",4,null,null,129]]\\n'. 
> Temporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.
> ```
> 
> The error you're experiencing isn't originating from the package itself; it's related to your Google account and may be due to various factors like your country or region settings, which can prevent you from receiving accurate results from Bard. Therefore, it's beyond the scope of the package to resolve, but please consider checking the following:
> 
>     1. First, thoroughly read the readme and see if it pertains to cases of temporary abnormal responses from the package. Try again after some time or a few hours: [Before using Bard API](https://github.com/dsdanielpark/Bard-API/blob/main/README.md#before-using-the-bard-api)
> 
>     2. Bypass proxies: [Behind a proxy](https://github.com/dsdanielpark/Bard-API#behind-a-proxy)
> 
>     3. Try using an account from a different region or change the language settings of your Google account.
> 
>     4. Restart your browser to refresh the cookie values and use the new __Secure-1PSID.
> 
>     5. Try passing three or more cookies using [Multi-cookie Bard](https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_DEV.md#multi-cookie-bard). If that doesn't work, consider passing almost all cookie values.
> 
> 
> Please let me know if you need further assistance.

I solved this problem in the following way. I replaced the User-Agen value in SESSION_HEADERS with the browser from which I got the token. And it started working.
