### ISSUE TITLE
Exception: Response status code is not 200. Response Status is 429 when trying to connect

### ISSUE THREAD

**Issue by Olinari** [dsdanielpark/Bard-API#208]
<img width="663" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/17886605/1cb543c8-d5b1-4665-9d06-2f0268f3eeda">

```
Traceback (most recent call last):
  File "/Users/arielolin/IAPP-server/server.py", line 20, in <module>
    bard = Bard(token=BARD_TOKEN, session=bard_session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bardapi/core.py", line 78, in __init__
    self.SNlM0e = self._get_snim0e()
                  ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bardapi/core.py", line 149, in _get_snim0e
    raise Exception(
Exception: Response status code is not 200. Response Status is 429
```

**Comment by Ducvoccer** [comment]
any update?

**Comment by dsdanielpark** [comment]
Both are not package-related issues and are unsolvable problems. It is recommended to work around them as much as possible. This is a problem at the level of Google's API, and while it would take a long time to develop software to work around it, even assuming that it could be developed, it is not worth developing because it is easily blocked. There are no plans to update it further. There is no package-level solution to prevent captcha or HTTP 429 errors other than efforts such as bypassing readme and proxy, and creating a time interval between requests to avoid rate limiting.
- CAPTCHA: a program or system intended to distinguish human from machine input, typically as a way of [thwarting](https://www.google.com/search?sca_esv=573532060&sxsrf=AM9HkKmd5Faz1q0x4sLsgIG3VgVR9V18iA:1697335053753&q=thwarting&si=ALGXSlbSiMNWMsv5Y0U_0sBS8EWzwSlNZdPczeDdDqrhgxYO86hMDzIqBVTJp6ZKxKdXeVsCSihVIJAH_MROqwPM7RtQB0OoEA%3D%3D&expnd=1) spam and automated extraction of data from websites.
- The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting")
