### ISSUE TITLE
TypeError: 'type' object is not subscriptable.

### ISSUE THREAD

**Issue by lenijwp** [dsdanielpark/Bard-API#228]
I use python 3.8 but such a issue comes.  When  I import the package , there is a :
from bardapi.models.result import BardResult
 
 from bardapi.models.result import BardResult
TypeError: 'type' object is not subscriptable.

So Could you tell me which is the correct python version.

**Comment by dsdanielpark** [comment]
#225 

Solution: Reinstall with the GitHub dev version or use Python version 3.9 or higher.

Are you using the GitHub dev version or the PyPI version 0.1.38? It seems like you might be using the GitHub dev version. If that's the case, since Python officially supports typing starting from version 3.9, please upgrade your Python version to 3.9 or higher, or update to the current GitHub dev version. (For the current GitHub dev version of bardapi, there is no issue with type hints even on Python versions 3.8 and below because we have imported a separate module to handle it.)
