### ISSUE TITLE
bard api 404

### ISSUE THREAD

**Issue by luoysuan** [dsdanielpark/Bard-API#229]
**Describe the bug**
Use bard api 404
**Version**
OS: win10
Python: 3.11
Bard API:  0.1.38  
Using proxy:
Legion:

**Code**
![1699838489832](https://github.com/dsdanielpark/Bard-API/assets/51365362/246d0c09-12cb-4145-a493-4df00fb99ac5)

**Comment by dsdanielpark** [comment]
The HTTP 409 Conflict response status code indicates a request conflict with the current state of the target resource. Conflicts are most likely to occur in response to a PUT request.

It seems there is a conflict with the local resources designated as a proxy server because the local server is unable to act as a proxy. I recommend using an appropriate proxy server.

**Comment by ashishkurian** [comment]
@dsdanielpark I am also getting the same error. Only difference is that, I am executing my python script from inside my wsl2.

<img width="948" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/16349403/c5c72721-6600-4655-b030-a060d5de45cb">

Code
```
import bardapi
import os

token = "*************"

input_text = "How much is one mile in kilometers"

response = bardapi.core.Bard(token).get_answer(input_text)
```
