### ISSUE TITLE
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. mediapipe 0.10.8 requires protobuf<4,>=3.11, but you have protobuf 4.25.1 which is incompatible. tensorboard 2.15.1 requires protobuf<4.24,>=3.19.6, but you have protobuf 4.25.1 which is incompatible.

### ISSUE THREAD

**Issue by lamachine** [dsdanielpark/Bard-API#237]
**Describe the bug**
Followed ReadMe and got red error in title.  I went on and installed git hub install listed next in readme without error.  

**Version**
OS: Win 11
Python: 3.10
Bard API:  bardapi-0.1.38-py3-none-any.whl.metadata (21 kB)
Using proxy: No
Legion: ?? 

**Code**
```
from bardapi import Bard 

token = 'xxxxxxx'
bard = Bard(token=token)
bard.get_answer("what is most pressing risk from AI")
```

**Error**
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. mediapipe 0.10.8 requires protobuf<4,>=3.11, but you have protobuf 4.25.1 which is incompatible. tensorboard 2.15.1 requires protobuf<4.24,>=3.19.6, but you have protobuf 4.25.1 which is incompatible.

**Comment by dsdanielpark** [comment]
This error does not appear to stem from a dependency package of Bard API. However, it seems to be recommended to downgrade the package version as follows.

On Python 3.11 and Windows 11, other dependency packages may not operate smoothly.

To resolve this issue, you need to install a version of `protobuf` that is compatible with both `mediapipe` and `tensorboard`. Since both require a version less than 4, you could try downgrading `protobuf` to a version that satisfies both packages, such as:

```bash
pip install protobuf==3.19.6
```

Before doing this, it's often a good idea to create a virtual environment to avoid affecting other Python projects or system packages.

After downgrading, you can verify that the correct versions are installed and there are no conflicts by running:

```bash
pip check
```

This command will check for any incompatibilities in installed package dependencies. If there are no conflicts, it won't output anything. If there are still conflicts, it will list them, and you may need to adjust the versions further.
