### ISSUE TITLE
error :v

### ISSUE THREAD

**Issue by jojo989** [dsdanielpark/Bard-API#24]
when i try to execute the first simple usage script it give me this error: raise Exception(
Exception: __Secure-1PSID value must end with a single dot. Enter correct __Secure-1PSID value.

**Comment by 24WOK** [comment]
i am too

**Comment by dsdanielpark** [comment]
As the error says, it happens when you enter the wrong __Secure-1PSID. 

__Secure-1PSID MUST end with a single dot, various other errors can be found in #1.

ex) os.environ['__BARD_API_KEY'] = VwhV4124qhvFp3nOm_sSsLszdr2u_DWm8otZBt3hPR9fud2BePGTk2jQmGmfcbKb_vyr3IjJFKEP.

Closing this issue as duplicate with #1.
