### ISSUE TITLE
Bard doesn't remember on rerun

### ISSUE THREAD

**Issue by tinker1234** [dsdanielpark/Bard-API#251]
bard doesn't remember on rerun whats the conversation id used for im passing it to bardcookies but it still wont remember past conversation

**Comment by dsdanielpark** [comment]
This issue cannot be supported at the bardapi package level. 

Officially, chatgpt has recently fixed the seed and retains the conversation, but Bard still appears to have different IDs for multi-choice. In other words, there are no options to fix the stream option and seed like chatgpt, and the only way is to keep appending previous conversation in a certain format.

Since this requires modifications at Google's official model server level, we have to close this issue as something that cannot be supported at the package level. We appreciate you checking for any duplicate issues. (We will update if it is supported in the future.)

Thank you.

#99 opened on Jul 12 by [ranjan-sumit](https://github.com/dsdanielpark/Bard-API/issues?q=is%3Aissue+is%3Aopen+author%3Aranjan-sumit)

#59 opened on Jun 10 by [BabaYaga1221](https://github.com/dsdanielpark/Bard-API/issues?q=is%3Aissue+is%3Aopen+author%3ABabaYaga1221)


#30 by [MohitSM18](https://github.com/dsdanielpark/Bard-API/issues?q=is%3Aissue+author%3AMohitSM18) was closed on May 23

#19 by [CatAnonymous](https://github.com/dsdanielpark/Bard-API/issues?q=is%3Aissue+author%3ACatAnonymous) was closed on May 19

#15 by [debayangg](https://github.com/dsdanielpark/Bard-API/issues?q=is%3Aissue+author%3Adebayangg) was closed on May 18
