### ISSUE TITLE
There should be with an option of ask_about_image without translator.

### ISSUE THREAD

**Issue by SetoKaiba** [dsdanielpark/Bard-API#252]
**Describe the bug**
I use zh-CN. It's supported by Bard directly. I should not need GoogleTranslator.
I can make it working with removing the code of GoogleTranslator.

**Version**
OS: Win
Python: 3.10
Bard API: latest in git
Using proxy: Yes
Legion: 

**Code**
```python
bard = Bard(token=token)
image = open('aaaaa.png', 'rb').read()
response = bard.ask_about_image('给我个列表，日期、金额、备注。', image)
print(response['content'])
```

**Error**
```
Traceback (most recent call last):
  File "E:\PycharmProjects\testGemini\test2.py", line 6, in <module>
    response = bard.ask_about_image('给我个列表，日期、金额、备注。', image)
  File "E:\PycharmProjects\testGemini\.venv\lib\site-packages\bardapi\core.py", line 674, in ask_about_image
    translator_to_eng = GoogleTranslator(source="auto", target="en")
NameError: name 'GoogleTranslator' is not defined
```

**Comment by SetoKaiba** [comment]
It seems that I can use the `get_answer` with image instead. So, why does `ask_about_image` exist? It is unnecessary.

**Comment by dsdanielpark** [comment]
Finally, I have some time, so I will proceed with the work. I will work on the backlog tasks and test them together before deploying. Please test it with the GitHub version before deployment. Once it's completed, I will close the issue.

Furthermore, the current package structure has become more complex than anticipated due to the increasing functionality. Any contributor is welcome to contribute and refactor freely. We warmly welcome active pull requests. We hope to create this project together. 

Thank you all. (However, if possible, please make sure to conduct at least some functional testing, even if you can't perform mocking.)

**Comment by dsdanielpark** [comment]
Considering that the majority are English speakers (including researchers), I've made adjustments so that if no language option is specified, the conditions are quickly bypassed.

Now, for English, responses are produced rapidly without extensive condition checks.

This was initially developed to alleviate language barriers more quickly, but it seems there was a misalignment due to accepting a PR from another contributor who efficiently modified the conditions without a thorough code review. This will be applied from version 0.1.39. 

Thank you.

**Comment by dsdanielpark** [comment]
To resover this name error, 
```
NameError: name 'GoogleTranslator' is not defined
```
Try to install deep translator
```
pip install deep_translator
```

**Comment by SetoKaiba** [comment]
@dsdanielpark Why not just not create the translator while lang is None and lang is None. It's not used later. There's no need for langdetect, deep_translator and google-cloud-translate.
https://github.com/dsdanielpark/Bard-API/blob/ddf4c22035ad8525604103d2e1a379d6b973f371/bardapi/core.py#L668-L673
Change to
```python
        if self.google_translator_api_key is not None:
            google_official_translator = translate.Client(
                api_key=self.google_translator_api_key
            )
        elif self.language is not None or lang is not None:
            translator_to_eng = GoogleTranslator(source="auto", target="en")
```

**Comment by dsdanielpark** [comment]
I have fixed it. Thank you.
