### ISSUE TITLE
Gemini Ultra?

### ISSUE THREAD

**Issue by ttuleyb** [dsdanielpark/Bard-API#279]
**Solution you'd like**

Hello, I'd like a togglable parameter that lets me use Gemini Ultra (Gemini Advanced) rather than the base version. I'm currently trying to reverse engineer the new Gemini API but its proving to be difficult with all the obfuscation Google is doing.

Thank you.

**Comment by birdup000** [comment]
I want that too, it would be nice to have that.

**Comment by opnoice** [comment]
I want that too, it would be nice to have that.

**Comment by dsdanielpark** [comment]
Currently, debugging and updating the package are delayed due to difficulty in accessing the core maintainer's Gemini. We will strive to update the package as soon as possible, even if it means hand-coding. 

We will also look into the mentioned feature. Thank you for your valuable feedback.

Additionally, I always welcome contributions from the open community and contributors. Please feel free to submit a pull request anytime. Thank you.

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API
