### ISSUE TITLE
ask_about_image Not working

### ISSUE THREAD

**Issue by galihmrd** [dsdanielpark/Bard-API#284]
**Describe the bug**
I tried using the ask_about_image function, but it doesn't work now.

**Version**
OS: ubuntu
Python: 3.11
Bard API: 0.1.40
Using proxy: No

**Code**
```python
from bardapi import Bard

bard = Bard(token='xxxxxxx')
image = open('image.jpg', 'rb').read() # (jpeg, png, webp) are supported.
bard_answer = bard.ask_about_image('What is in the image?', image)
print(bard_answer['content'])
```

**Error**
```
cannot access local variable 'translated_input_text' where it is not associated with a value
```

**Comment by dsdanielpark** [comment]
[galihmrd](https://github.com/galihmrd)

Hello, Thank you for reporting. We are making modifications to accommodate the new Gemini API. Our goal is to update within 48 hours. However, due to limited access to Gemini at the moment, our progress is delayed. Please bear with us and stay tuned. Alternatively, anyone is welcome to contribute by creating a pull request at any time. Thank you.

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API
