### ISSUE TITLE
Response Error

### ISSUE THREAD

**Issue by Sumant-Testbook** [dsdanielpark/Bard-API#33]
{'content': 'Response Error: b\')]}\\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[8]]]\\n56\\n[["di",75],["af.httprm",75,"-8694801941071849458",37]]\\n25\\n[["e",4,null,null,131]]\\n\'.'}

Such Response is observed while running bard.get_answer("Generate Html an Js for Mean Calculator")

**Comment by dsdanielpark** [comment]
1. Please check if you can have a conversation with Bard successfully by visiting https://bard.google.com/.
2. If you can engage in a conversation, please make sure to repeatedly check if the __Secure-1PSID cookie is being properly inputted. Try several times to ensure accuracy.
3. Test in various environments to ensure compatibility.
4. 
For other errors, please refer to the following issue #1 . Since it is a duplicate issue, I will close this one.
