### ISSUE TITLE
Why Timeout Error Coming?

### ISSUE THREAD

**Issue by Ali-Shahab** [dsdanielpark/Bard-API#70]
ut
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='bard.google.com', port=443): Read timed out. (read timeout=20)   

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali.shahab\Desktop\Ali'S Folder\test\bard.py", line 17, in <module>
    response = bardapi.core.Bard(token).get_answer(pre_prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\bardapi\core.py", line 105, in get_answer
    resp = self.session.post(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali.shahab\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by dsdanielpark** [comment]
If a response for a request is not received within a certain period of time, a timeout error occurs. This is a response to an incomplete internet connection or delayed response time. Developers have the option to handle different reactions instead of a timeout error. If you want to receive the result even with a delay and without such an error, please set the timeout variable to a sufficiently large number.

**Comment by Ali-Shahab** [comment]
here is my source code, how can i? 

try:
    response = bardapi.core.Bard(token).get_answer(pre_prompt)
    print(response['content'].replace('*',' '))

**Comment by dsdanielpark** [comment]
Check [this section](https://github.com/dsdanielpark/Bard-API#usage). 

```python
response = bardapi.core.Bard(token=token, timeout=120).get_answer(pre_prompt)
```

**Comment by Ali-Shahab** [comment]
thanks dude
