### ISSUE TITLE
Pre prompt like GPT

### ISSUE THREAD

**Issue by Ali-Shahab** [dsdanielpark/Bard-API#71]
Just like OPENAI library has parameters like prompt where we put instruction to it. For example: Act like a mychatbot who's name is Toranto. so it will act like Toranto. Can't we do the same with bardapi?

**Comment by dsdanielpark** [comment]
You can create the following in a dictionary format and provide it as input along with the user prompt. It is not a particularly difficult or complex task, but Bard is still incomplete, and since each user may have different desired prompts, I haven't implemented the task specifically. I recommend that you simply append the necessary content in string format to your prompt.

https://github.com/dsdanielpark/amazing-bard-prompts

**Comment by Ali-Shahab** [comment]
i am trying to do it by string interpolation method but some times it is not working. 
 input_text = "tell me about jarvis"
    info = "You are chatbot named Ironman."
    pre_prompt = (f'{info} These are your instruction now just reply to this message which is{input_text}') 
basically i am trying to give bard intruction like that but its not working properly and the above link you mentioned does'nt have any code
