### ISSUE TITLE
chatbot deploy error

### ISSUE THREAD

**Issue by Quantum-MIT** [dsdanielpark/Bard-API#74]
i created a chatbot using bard api and streamlit when i deployed it, the chatbot gives a response error ? please tell a possible solution. Only in localhost, it is working correctly

**Comment by dsdanielpark** [comment]
If it functions properly on localhost but you're unsure about the exact server environment, there is a possibility that your server is behind a proxy server or that port forwarding is being used.

In such cases, please refer to the following [Behind a proxy](https://github.com/dsdanielpark/Bard-API#behind-a-proxy).

Due to the numerous possibilities and the lack of specific information, I'm unable to provide further assistance. Since it is not an issue with the package itself, I will close the issue.
