### ISSUE TITLE
why keyerror "image" happens

### ISSUE THREAD

**Issue by Xiansssss** [dsdanielpark/Bard-API#88]
<img width="830" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/82095274/b9333272-0083-4bc4-8268-df068e3c0bb4">
I'm wondering why the error pops up, even we can use the try except to handle this, but nothing changes. If I input a normal text like :"hi", it will return nothing since it's still be recognized as an error.

Thanks a lot.

**Comment by orsnaro** [comment]
_possibly due to  a typo in `Bard` class imported to `chat.py`_

[Bard Class typo line](https://github.com/dsdanielpark/Bard-API/blob/main/bardapi/core.py#L85)  ❌`"imgaes"` -> ✅`"images"`

[BardAsync Class typoe line](https://github.com/dsdanielpark/Bard-API/blob/main/bardapi/core_async.py#L78) ❌`"imgaes"` -> ✅`"images"`

**Comment by dsdanielpark** [comment]
Could you please confirm if you have checked the Bard.get_answer method for the same error as before? Additionally, could you restart the Colab session and update the version of bardapi for verification? Please note that in some countries, there may be issues with IP-related functionality, and in such cases, you may need to check and adjust your settings, such as using a proxy. However, there are too many variables involved in this situation, and I apologize that I cannot provide assistance in such cases. Thank you for your understa
```
pip install bardapi==0.1.22
```
