### ISSUE TITLE
Error: Temporarily unavailable due to traffic or an error in cookie values.

### ISSUE THREAD

**Issue by tiagorangel2011** [dsdanielpark/Bard-API#92]
I'm getting this error:
```
Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",70],["af.httprm",70,"-XXXXXXXXXXXXXXXXXXXX",29]]\n25\n[["e",4,null,null,131]]\n'. 
Temporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.
```
This is my code:
```
from bardapi import Bard
token = '************************************************'
bard = Bard(token=token)
print(bard.get_answer("Hi Bard!")['content'])
```
I am in a country that is not available to Bard (I'm in the EU), so I could only get the token using Opera VPN, but Opera VPN is not for the whole internet, so the request does NOT get covered by the VPN.  If this is the cause of the problem, are there any workarounds?

**Comment by dsdanielpark** [comment]
Please refer to the following information. 

[behind a proxy](https://github.com/dsdanielpark/Bard-API#behind-a-proxy) #76 #1 

Additionally, the mentioned response error is caused by Google's internal interface policies, network issues, and other environmental factors, rather than the bardapi package. We apologize for any inconvenience and limitations in providing further assistance. Feel free to discuss your similar challenges with others.

**Comment by tiagorangel2011** [comment]
I have solved this by using a VPN that works for my whole computer, not only the browser.

Caused by being in a country where Google Bard is not supported (yet, I'm in the EU). Closing.
