### ISSUE TITLE
ContextualVersionConflict

### ISSUE THREAD

**Issue by devmehta01** [dsdanielpark/Bard-API#93]
Received the following error when trying to import Bard.

ContextualVersionConflict: (google-auth 2.16.2 (d:\softwares\anaconda\envs\drive_thru\lib\site-packages), Requirement.parse('google-auth<2.0dev,>=1.24.0'), {'google-cloud-core'})

**Comment by dsdanielpark** [comment]
It seems like there is a conflict due to the dependency on the official API package from Google Cloud for some multilingual translations. Please try removing the mentioned content and install it again. Also, make sure to verify that it has been properly uninstalled and reinstalled.

```
pip uninstall bardapi
```

```
pip install bardapi --no-dependencies google-cloud-translate==2.0.1
```

**Comment by devmehta01** [comment]
Thanks @dsdanielpark. I created another environment but it still gave the same error. I then installed google-cloud-core with 1.24.0 version and that solved the issue. Had to install a few other things as well and then it worked. However, I now get the following error:
'Response Error: b\')]}\\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[9]]]\\n54\\n[["di",89],["af.httprm",89,"7855032709640118140",8]]\\n25\\n[["e",4,null,null,129]]\\n\'. \nTemporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.'

I saw other issues raised, and from what I understood, there is no solution to this and just to maybe wait and try again?

**Comment by dsdanielpark** [comment]
Yes, that's correct. 

As you have reviewed, there is no solution to this error. This error occurs due to various reasons such as country, region, account, network status, proxy, VPN, and other factors based on Google's internal interfaces and API policies, unrelated to bardapi.

Therefore, please understand that there are no measures or solutions that can be taken within the bardapi project.

For developers who are implementing certain features, it is possible to mock this error message and continue development. However, there is still no way to receive a valid response.

We also appreciate the report of the following error and the suggestions for resolving it. Your issue will be of great help to others. We apologize for not being able to provide further assistance at this time. If we can be of help in the future, please let us know, and we will gladly assist you.

We apologize for not being able to provide assistance. Thank you.



<br><br>



### Error Message
```
ContextualVersionConflict: (google-auth 2.16.2 (d:\softwares\anaconda\envs\drive_thru\lib\site-packages), Requirement.parse('google-auth<2.0dev,>=1.24.0'), {'google-cloud-core'})
```



>  I created another environment but it still gave the same error. I then installed google-cloud-core with 1.24.0 version and that solved the issue. Had to install a few other things as well and then it worked. However, I now get the following error: 'Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n54\n[["di",89],["af.httprm",89,"7855032709640118140",8]]\n25\n[["e",4,null,null,129]]\n'. \nTemporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.'
> 
> I saw other issues raised, and from what I understood, there is no solution to this and just to maybe wait and try again?

**Comment by devmehta01** [comment]
@dsdanielpark Thanks a lot for your timely responses and your help. It's a bummer that there is no solution for this and hopefully, bard will release their official API soon! Thanks again!
