### ISSUE TITLE
Getting Response Error when making continuous requests

### ISSUE THREAD

**Issue by raaj1v** [dsdanielpark/Bard-API#95]
Loop through your list of product names
for i, row in df.iterrows():
product = row['productsManufactured']
print("Product", product)

https://user-images.githubusercontent.com/86911408/251436785-0613e180-e906-4e12-a16f-c6edea1de0dd.png

# Get CPV code
cpv_code = Bard(token=token).get_answer(f"The CPV code for {product} is ")['content']
print("cpv_code", cpv_code)
# Store CPV code in dataframe
df.at[i, 'CPVCode'] = cpv_code
Above is my code, but the issue i'm facing is getting response error (I have around 17000 product names, but i'm trying for just 150 at a time, even then i'm getting error after continued response for 120. after waiting for 3-5 hours, it works fine for the next 120 names) . Can you please help me if there's anyway to resolve this. or why it's happening, and if it can be by bypassed by using several tokens and proxies?

any help would be highly appreciated

**Comment by dsdanielpark** [comment]
As mentioned in the project's README.md and in other issues, bardapi is an unofficial personal project. This project is designed to temporarily provide developers with some functionality to explore before the official release of the Google bard API.

The experimental version of bard is not free, and the return values of this project are also not free. Therefore, we do not recommend generating a large amount of traffic or using it for specific purposes. Additionally, the cookie referred to as an API key is tied to your account, which means that Google can track your actions and potentially impose permanent blocking, rather than temporary blocking.

We suggest considering the use of other llm models available under the Apache License or exploring alternative methods.

Please note that this project is temporary and not permanent, and it does not assume any explicit or implicit responsibility. All responsibility lies with the user. Thank you.
